/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppContext, AppEvent, AppSchema, MachineInterpreter, MachineState } from "./machine";
export namespace Components {
    interface V4fApp {
    }
    interface V4fScreenActivities {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenHome {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenLocations {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenRentals {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenService {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenServices {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
}
declare global {
    interface HTMLV4fAppElement extends Components.V4fApp, HTMLStencilElement {
    }
    var HTMLV4fAppElement: {
        prototype: HTMLV4fAppElement;
        new (): HTMLV4fAppElement;
    };
    interface HTMLV4fScreenActivitiesElement extends Components.V4fScreenActivities, HTMLStencilElement {
    }
    var HTMLV4fScreenActivitiesElement: {
        prototype: HTMLV4fScreenActivitiesElement;
        new (): HTMLV4fScreenActivitiesElement;
    };
    interface HTMLV4fScreenHomeElement extends Components.V4fScreenHome, HTMLStencilElement {
    }
    var HTMLV4fScreenHomeElement: {
        prototype: HTMLV4fScreenHomeElement;
        new (): HTMLV4fScreenHomeElement;
    };
    interface HTMLV4fScreenLocationsElement extends Components.V4fScreenLocations, HTMLStencilElement {
    }
    var HTMLV4fScreenLocationsElement: {
        prototype: HTMLV4fScreenLocationsElement;
        new (): HTMLV4fScreenLocationsElement;
    };
    interface HTMLV4fScreenRentalsElement extends Components.V4fScreenRentals, HTMLStencilElement {
    }
    var HTMLV4fScreenRentalsElement: {
        prototype: HTMLV4fScreenRentalsElement;
        new (): HTMLV4fScreenRentalsElement;
    };
    interface HTMLV4fScreenServiceElement extends Components.V4fScreenService, HTMLStencilElement {
    }
    var HTMLV4fScreenServiceElement: {
        prototype: HTMLV4fScreenServiceElement;
        new (): HTMLV4fScreenServiceElement;
    };
    interface HTMLV4fScreenServicesElement extends Components.V4fScreenServices, HTMLStencilElement {
    }
    var HTMLV4fScreenServicesElement: {
        prototype: HTMLV4fScreenServicesElement;
        new (): HTMLV4fScreenServicesElement;
    };
    interface HTMLElementTagNameMap {
        "v4f-app": HTMLV4fAppElement;
        "v4f-screen-activities": HTMLV4fScreenActivitiesElement;
        "v4f-screen-home": HTMLV4fScreenHomeElement;
        "v4f-screen-locations": HTMLV4fScreenLocationsElement;
        "v4f-screen-rentals": HTMLV4fScreenRentalsElement;
        "v4f-screen-service": HTMLV4fScreenServiceElement;
        "v4f-screen-services": HTMLV4fScreenServicesElement;
    }
}
declare namespace LocalJSX {
    interface V4fApp {
    }
    interface V4fScreenActivities {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenHome {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenLocations {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenRentals {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenService {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface V4fScreenServices {
        "service": MachineInterpreter<AppContext, AppSchema, AppEvent>;
        "state": MachineState<AppContext, AppEvent, AppSchema>;
    }
    interface IntrinsicElements {
        "v4f-app": V4fApp;
        "v4f-screen-activities": V4fScreenActivities;
        "v4f-screen-home": V4fScreenHome;
        "v4f-screen-locations": V4fScreenLocations;
        "v4f-screen-rentals": V4fScreenRentals;
        "v4f-screen-service": V4fScreenService;
        "v4f-screen-services": V4fScreenServices;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "v4f-app": LocalJSX.V4fApp & JSXBase.HTMLAttributes<HTMLV4fAppElement>;
            "v4f-screen-activities": LocalJSX.V4fScreenActivities & JSXBase.HTMLAttributes<HTMLV4fScreenActivitiesElement>;
            "v4f-screen-home": LocalJSX.V4fScreenHome & JSXBase.HTMLAttributes<HTMLV4fScreenHomeElement>;
            "v4f-screen-locations": LocalJSX.V4fScreenLocations & JSXBase.HTMLAttributes<HTMLV4fScreenLocationsElement>;
            "v4f-screen-rentals": LocalJSX.V4fScreenRentals & JSXBase.HTMLAttributes<HTMLV4fScreenRentalsElement>;
            "v4f-screen-service": LocalJSX.V4fScreenService & JSXBase.HTMLAttributes<HTMLV4fScreenServiceElement>;
            "v4f-screen-services": LocalJSX.V4fScreenServices & JSXBase.HTMLAttributes<HTMLV4fScreenServicesElement>;
        }
    }
}
